/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp fileassociation_necessaries.xml -a FA_Adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FA_ADAPTOR_H
#define FA_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
//class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface file.association
 */
class AssociationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "file.association")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"file.association\">\n"
"    <signal name=\"ServiceAdded\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service_domain\"/>\n"
"    </signal>\n"
"    <signal name=\"TypeAdded\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service_domain\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"type_name\"/>\n"
"    </signal>\n"
"    <signal name=\"ServiceRemoved\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service_domain\"/>\n"
"    </signal>\n"
"    <signal name=\"TypeRemoved\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service_domain\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"type_name\"/>\n"
"    </signal>\n"
"    <signal name=\"GotTypes\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"service_domain\"/>\n"
"    </signal>\n"
"    <method name=\"addService\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"    </method>\n"
"    <method name=\"addType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"type_name\"/>\n"
"    </method>\n"
"    <method name=\"removeService\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"    </method>\n"
"    <method name=\"removeType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"type_name\"/>\n"
"    </method>\n"
"    <method name=\"getTypes\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"    </method>\n"
"    <method name=\"serviceExist\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"service_domain\"/>\n"
"    </method>\n"
"    <method name=\"getServices\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"    </method>\n"
"    <method name=\"getServicesByType\">\n"
"      <arg direction=\"out\" type=\"as\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"type_name\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AssociationAdaptor(QObject *parent);
    virtual ~AssociationAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void addService(const QString &service_domain);
    void addType(const QString &service_domain, const QString &type_name);
    QStringList getServices();
    QStringList getServicesByType(const QString &type_name);
    QStringList getTypes(const QString &service_domain);
    void removeService(const QString &service_domain);
    void removeType(const QString &service_domain, const QString &type_name);
    bool serviceExist(const QString &service_domain);
Q_SIGNALS: // SIGNALS
    void GotTypes(const QString &service_domain);
    void ServiceAdded(const QString &service_domain);
    void ServiceRemoved(const QString &service_domain);
    void TypeAdded(const QString &service_domain, const QString &type_name);
    void TypeRemoved(const QString &service_domain, const QString &type_name);
};

#endif
